// <auto-generated />
namespace MySelf.Diab.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class SecurityLink_Link_Index_Unique : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SecurityLink_Link_Index_Unique));
        
        string IMigrationMetadata.Id
        {
            get { return "201308230924045_SecurityLink_Link_Index_Unique"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
