// <auto-generated />
namespace MySelf.Diab.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class SecurityLinkUniqueIndex : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SecurityLinkUniqueIndex));
        
        string IMigrationMetadata.Id
        {
            get { return "201308230918146_SecurityLinkUniqueIndex"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
