// <auto-generated />
namespace MySelf.Diab.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddedFoodAndFoodTypes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedFoodAndFoodTypes));
        
        string IMigrationMetadata.Id
        {
            get { return "201512030915302_AddedFoodAndFoodTypes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
