// <auto-generated />
namespace MySelf.Diab.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RefactoredFoodTypesAsString : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RefactoredFoodTypesAsString));
        
        string IMigrationMetadata.Id
        {
            get { return "201512061815239_RefactoredFoodTypesAsString"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
